### ISSUE TITLE
Translate to Chinese

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint.org#165]
### What language do you want to translate the website into?

chinese

### What is the language code for the language?

zh

### What is the locale code for the language?

zh-cn

### What help will you need?

Not yet. we already had a repo(https://github.com/eslint/cn.eslint.org), just need to copy to here.
cc @QC-L

### Implementation Checklist

- [x] Create new site file
- [x] Set up Netlify project
- [x] Register new domain name
- [x] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks! I was going to loop in the folks on can.eslint.org once we also had a solution for the docs, but no harm in getting started now.

**Comment by nzakas** [comment]
Site is live:
http://new.cn.eslint.org/

I'll work on getting Google Analytics and ads for it (if possible)

**Comment by nzakas** [comment]
Adding analytics in #202.

**Comment by kecrily** [comment]
@nzakas new.cn.eslint.org is using an invalid certificate. It shows that the certificate issued to `*.netlify.app` is being used. Please check it

![image](https://user-images.githubusercontent.com/45708948/168215710-d8d8c332-af67-41c3-a7f6-84b515457798.png)

**Comment by nzakas** [comment]
Thanks. It should be fixed momentarily.

**Comment by kecrily** [comment]
It doesn't seem to be fixed yet.

**Comment by nzakas** [comment]
Looks like the certificate creation failed. I’ll need to contact support.

**Comment by kecrily** [comment]
I noticed that the main site is now using the new version, so maybe it's time to deploy the Chinese site to cn.eslint.org, not new.cn.eslint.org

----

Also maybe consider using zh.eslint.org instead of cn.eslint.org. other language sites are using language codes instead of country codes, and I don't think Chinese should be an exception.

**Comment by aladdin-add** [comment]
https://github.com/eslint/cn.eslint.org/issues/218

**Comment by aladdin-add** [comment]
closing as fixed. 🎉
