### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by stefankolb** [eslint/eslint.org#187]
### What language do you want to translate the website into?

German

### What is the language code for the language?

de

### What is the locale code for the language?

de-DE

### What help will you need?

For now, no help needed.

### Implementation Checklist

- [ ] Create new site file
- [ ] Set up Netlify project
- [ ] Register new domain name
- [ ] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

It will probably take me several weeks to finish the translations, so if you guys are in a hurry to get this done, I may not be the right person for this task.

**Comment by nzakas** [comment]
No hurry at all! Take your time and we appreciate the contribution. Let us know if you need any help along the way.

**Comment by nzakas** [comment]
@stefankolb just checking back to see if you are still intending to work on this?

**Comment by stefankolb** [comment]
@nzakas Yes, absolutely, I'm 80% done, testimonials and faq are what's left. Sorry it takes so long

**Comment by nzakas** [comment]
No problem at all! We appreciate your effort.
