### ISSUE TITLE
Translate to Hindi

### ISSUE THREAD

**Issue by snitin315** [eslint/eslint.org#191]
### What language do you want to translate the website into?

Hindi

### What is the language code for the language?

hi

### What is the locale code for the language?

hi_IN

### What help will you need?

Nothing at the moment.

### Implementation Checklist

- [x] Create new site file
- [x] Set up Netlify project
- [x] Register new domain name
- [x] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I will take a few weeks for this.

**Comment by nzakas** [comment]
Awesome! Will be interested to see how the layout holds up in Hindi.

**Comment by nzakas** [comment]
The site is now deployed: https://hi.eslint.org.

I've added analytics in #202

Checking on ads

**Comment by nzakas** [comment]
No ads, so closing.
