### ISSUE TITLE
Keep `eslintbot` in `all_authors.json`

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint.org#238]
We have added `eslintbot` into `all_authors.json` because it will be the default author for release blog posts.

But our data update script overwrites `all_authors.json` with the list of authors from existing blog posts, so it will always remove `eslintbot`. This just happened in https://github.com/eslint/new.eslint.org/commit/db3b33b1f32db74219118b95359926f4f2ec856a

**Comment by nzakas** [comment]
This is happening in `fetch-team-data.js`. We should just merge data into the file instead of overwriting.

**Comment by amareshsm** [comment]
I would like give a try. Can I pick this?

**Comment by snitin315** [comment]
@amareshsm sure, feel free.
