### ISSUE TITLE
Translate to Brazilian Portuguese

### ISSUE THREAD

**Issue by Rodzman** [eslint/eslint.org#242]
### What language do you want to translate the website into?

Portuguese-BR

### What is the language code for the language?

pt-br

### What is the locale code for the language?

pt_BR

### What help will you need?

Help with the process after creating and commiting the file.

### Implementation Checklist

- [x] Create new site file
- [ ] Set up Netlify project
- [ ] Register new domain name
- [ ] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Awesome, thanks! Let us know when you have questions.

**Comment by nzakas** [comment]
:tada: https://pt-br.eslint.org/
