### ISSUE TITLE
The description of the donate page seems to use incorrect grammar

### ISSUE THREAD

**Issue by haykam821** [eslint/eslint.org#269]
### URL(s)

https://eslint.org/donate/

### What did you do?

The donate page uses the following description, which contains a grammatical error:

> ## Donate
>
> ESLint relies on donations for ongoing maintenance and development. There are currently 184 companies, organizations, and individuals are donating $9,337.00 each month to help us out.

This description is rendered from the following:

https://github.com/eslint/eslint.org/blob/5d13b11ea92f99db005b34e2d8af5cf5ebc7e9e2/src/_data/sites/en.yml#L385-L388

### What did you expect to happen?

I expected the description of the donate page to have correct grammar.

### What actually happened?

The description of the donate page uses two instances of 'are' in its final sentence, and the second of which seems incorrect without a leading 'which' or similar correction.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Yup, nice catch. Please feel free to open a pull request to fix this.
