### ISSUE TITLE
Bug: (from-the-blog partial contains harcoded word: "View all posts")

### ISSUE THREAD

**Issue by luifermoron** [eslint/eslint.org#277]
### URL(s)

https://github.com/eslint/eslint.org/blob/main/src/_includes/partials/from-the-blog.html#L12

### What did you do?

I just noticed it while navigating through the blogs

### What did you expect to happen?

replace the hardcoded word by a dynamic variable, so its content will change according to its language

### What actually happened?

since it is hardcoded only English version will be shown.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

already submit a PR: [276](https://github.com/eslint/eslint.org/pull/276)

**Comment by nzakas** [comment]
Thanks!
