### ISSUE TITLE
Suggestion: Improve UX of rules managing in Playground

### ISSUE THREAD

**Issue by pubmikeb** [eslint/eslint.org#278]
### What problem do you want to solve?

Since the https://eslint.org redesign, in order to add a rule in Playground you need to add it manually:
1. Click on `Choose a rule` combo box
2. Find a desired rule in a very long list of all available rules
3. Click on it
4. Click on `Add this rule`

This four steps you need to repeat manually for every rule you want to add. That's a tedious and time burning work.

### What do you think is the correct solution?

Just use an UX from the previous version of https://eslint.org, where you could just click on "Enable all rules" and moreover, all rules have been grouped by the types with a good visualization, which made it extremely easy to maintain an ESLint config.

Poor UX. It would take me hours to find and add all required rules:
![25_121209](https://user-images.githubusercontent.com/17231333/175769138-473e2fd2-56ab-4562-9e95-5e47329d05d1.png)
Plus, everytime I click on `Add this rule`, page is automatically scrolled to the place, where a rule has been added, then I need manually scroll back to the head of a page to add another rule. It's a torture!

Good UX. Just with several clicks get a perfect `eslintrc.json`:
![25_120844](https://user-images.githubusercontent.com/17231333/175769068-c4d7977a-efa0-4af7-bef8-6d9ef30085ff.png)
And the UI is clean, spacious and not to overloaded, in contrast to the new one.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Please, consider returning the former Playground UX, so we could generate `eslintrc.json` within several clicks.

**Comment by harish-sethuraman** [comment]
Are we considering to use a multi select for dropdown to add rules? If yes I can pick this up.

**Comment by nzakas** [comment]
@harish-sethuraman I think that depends on the design. As already mentioned, we don’t want to go back to checkboxes. If you have an idea for what it might look like, I’d suggest posting a design first before attempting to implement anything.

**Comment by harish-sethuraman** [comment]
<img width="563" alt="Screenshot 2022-08-09 at 10 02 01 AM" src="https://user-images.githubusercontent.com/32865581/183564776-aee6b7fe-e57e-4872-9832-a5d7092d6b4c.png">
@nzakas We are not going to move to checkboxes. We will use select that allows us to select multiple options like shown above.

**Comment by nzakas** [comment]
@harish-sethuraman I’m not sure how that solves the problem. Can you explain more about what the user experience would be like?

**Comment by harish-sethuraman** [comment]
I've sent a PR with multiselect instead of normal select. This way we don't need checkboxes and we can select multiple rules at once and then add them. ref preview: https://github.com/eslint/eslint.org/pull/308
