### ISSUE TITLE
Live reload for playground editor

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#280]
During development, the website will live reload if Eleventy-owned files are changed, but not if the React components are changed.

It would be great to also live reload when React components are changed to make development easier.

**Comment by Rodzman** [comment]
Hi @nzakas! How are you?

Is this issue still needing attention? If so, can I help in anyway?

Regards

**Comment by snitin315** [comment]
@Rodzman Yes, this is yet to be implemented. Feel free to send a PR
