### ISSUE TITLE
Playground Font

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint.org#281]
Is the font we're using considered suitable for coding? I personally find it very difficult to read code samples in this font, and round parentheses () next to each other are especially distracting as they look like a circle.

![image](https://user-images.githubusercontent.com/44349756/164566313-4a0920b3-f977-4069-92f6-b8007842d3c5.png)

**Comment by harish-sethuraman** [comment]
I think as we have turned of ligatures across sites we shouldn't have characters transforming into symbols. 

Also +1 to considering using some other font for code examples and playground. It would be nice if we went ahead with some fonts like https://github.com/tonsky/FiraCode or https://github.com/microsoft/cascadia-code that provides better programming ligatures

**Comment by nzakas** [comment]
The problem is that all of the fonts were chosen to work together as part of the design. Just switching out the monospaced font breaks the consistency we have everywhere and makes the website feel more generic.

With the ligatures off, I don’t really have a problem with the current font.

**Comment by nzakas** [comment]
Although, I wonder if we can solve this by creating our own font. Just start with Space Mono and replace all the characters we don't like with the equivalent from another font that we do like? That seems like we could address everyone's concerns. Maybe we could just hire someone to do that?
