### ISSUE TITLE
Update /team page with new team members

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#283]
We recently created two new teams, and we need to get those displayed on the /team page:

* Website Team - The people who maintain eslint.org.
* Support Team - The people who answer questions in Discord, on our mailing lists, and in discussions.

These should appear, in this order, on the /team page.

## Steps

- [ ] Update [`tools/fetch-team-data.js`](https://github.com/eslint/eslint.org/blob/main/tools/fetch-team-data.js) - I believe you just need to include the new teams in [this section](https://github.com/eslint/eslint.org/blob/main/tools/fetch-team-data.js#L37-L57) and then update [here](https://github.com/eslint/eslint.org/blob/main/tools/fetch-team-data.js#L100-L107). This will generate the `src/_data/team.json` file.
- [ ] Update the [HTML template](https://github.com/eslint/eslint.org/blob/main/src/content/pages/team.html)
- [ ] Add the strings for the team name and descriptions to each file in the `src/_data/sites` directory. It's okay to use English for all of the sites -- we will need to get those translated later.

**Comment by snitin315** [comment]
I'll work on it.

**Comment by nzakas** [comment]
Thanks!
