### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint.org#298]
### URL(s)

https://eslint.org/play/#eyJ0ZXh0IjoidmFyIGZvbyA9IFwiaGVsbG8gd29ybGRcIjtcblxuY29uc29sZS5sb2coZm9vKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLWxvbmVseS1pZiI6WyJlcnJvciJdLCJuby1lbHNlLXJldHVybiI6WyJlcnJvciJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==

### What did you do?

just open the above url.

### What did you expect to happen?

no errors.

### What actually happened?

![image](https://user-images.githubusercontent.com/13050025/183028162-08d9ab6d-cd23-4daf-9b2d-04ca194d22a8.png)

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

browser: Microsoft Edge Version 103.0.1264.77 (Official build) (x86_64)
os: macos

**Comment by nzakas** [comment]
@snitin315 please be sure to also move issues to the “Ready to Implement” column when marked as accepted.

**Comment by Tanujkanti4441** [comment]
![Screenshot 2022-08-08 231349](https://user-images.githubusercontent.com/86398394/183577662-437c656e-3a41-4c7e-9199-d78f88004464.png)

i am getting this error in my console on playground page i think it is related to this issue.
Can i make a PR for this.

**Comment by aladdin-add** [comment]
sure, go for it! 👍

**Comment by amareshsm** [comment]
closing this as completed in #305
