### ISSUE TITLE
Bug:  Uncaught TypeError: Cannot read properties of null (reading 'classList') in windows

### ISSUE THREAD

**Issue by shanpriyan** [eslint/eslint.org#301]
### URL(s)

https://eslint.org/play/

### What did you do?

1. On `windows`  OS
1. Open any browser and visit [playground](https://eslint.org/play/)
2. Open `console` in devtools

### What did you expect to happen?

- No errors in console
- Should add `win` to the body class, if site is opened on `windows` machine

### What actually happened?

Received `document.body` is null error in console

### Participation

- [X] I am willing to submit a pull request for this issue.

## Console
![image](https://user-images.githubusercontent.com/42532987/183131307-3ec20b0f-2787-4444-9024-8db71662b4a6.png)
## Source
![image](https://user-images.githubusercontent.com/42532987/183131344-b5966a62-8a1b-4367-a04c-c155414a25f0.png)

### Cause
Trying to access `document.body` from `head` tag https://github.com/eslint/eslint.org/blob/3fdd3964c4383b1f970f550aa887795a01bcc2d5/src/_includes/layouts/base.html#L128

**Comment by nzakas** [comment]
Thanks for the report!
