### ISSUE TITLE
Add keyboard controls to blog search

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#309]
Right now the blog search is mouse-only. We should update it to include keyboard controls:

1. After typing a couple characters, pressing down should move focus to the first search result and highlight it. You should be able to move to previous and next search results using up/down keys.
2. Pressing ESC should hide the dropdown and set focus back to the textbox.

**Comment by shanpriyan** [comment]
Shall i work on this?

**Comment by harish-sethuraman** [comment]
Sure, I think we will need to do the same inside docs directory in ESLint main repo as well.

**Comment by shanpriyan** [comment]
> Sure, I think we will need to do the same inside docs directory in ESLint main repo as well.

Sure

**Comment by nzakas** [comment]
Yes we will. I just thought it would be easier to start on the blog and then just copy things over to the docs site too.

**Comment by shanpriyan** [comment]
>2.Pressing ESC should hide the dropdown and set focus back to the textbox.

Currently, `Esc` key is clearing the search query and closing the dropdown. Should I change it only to hide the dropdown without clearing the search query?

**Comment by harish-sethuraman** [comment]
I think it is better to close the search results alone when `esc` is pressed instead of clearing the search result as well
