### ISSUE TITLE
Bug: Playground controls missing expand/collapse

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#310]
### URL(s)

https://eslint.org/play

### What did you do?

Navigated to the page

### What did you expect to happen?

I expected each section on the right configuration pane to be able to be collapsed or expanded.

### What actually happened?

There is no way to collapse or expand the panels.
![Screenshot 2022-08-12 at 11-02-53 ESLint Playground - ESLint - Pluggable JavaScript Linter](https://user-images.githubusercontent.com/38546/184418360-8482f4d2-38fa-4eb8-b968-a8e39497ee78.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This appears to be a regression. I remember we fixed this previously.

**Comment by harish-sethuraman** [comment]
I can pick this up

**Comment by nzakas** [comment]
Thanks! When you want to take something, please be sure to assign it to yourself, add the "accepted" label (once you've verified), and move to the "Ready to Implement" column in the Triage board. This helps us better keep track of things.
