### ISSUE TITLE
Suggestion: (place "dark mode switch" and "language selection" to the header position)

### ISSUE THREAD

**Issue by lovetingyuan** [eslint/eslint.org#317]
### What problem do you want to solve?

"dark mode change" and "language selection" are usually at the top of the website. 

### What do you think is the correct solution?

I think it is better to place "dark mode switch" and "language selection" to the header position.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by kecrily** [comment]
I support making the language switch more visible. However, the dark mode toggle may not be necessary because by default it follows the user's system preference.

**Comment by nzakas** [comment]
The problem is that we just don't have enough space at the top to fit all of these options, so we moved them to the bottom.

I'm willing to entertain an accessible design that somehow exposes the language options higher up, but we'd need it to work in a responsive way all the way down to mobile. If someone wants to propose something, we can consider it, but I don't think it's worth the team spending any time on.

**Comment by SaraSoueidan** [comment]
Chiming in with an opinion here:

Most websites have language switchers at the bottom of the site. So I don’t see the current position of the language switcher as a problem that needs to be solved. Same for the theme switcher: some sites have it at the top; others have it at the bottom. There's no right or wrong here.

Of course, the design dictates where something goes. As @nzakas mentioned, there's not enough space at the top to fit an accessible version of these switchers (one that has labels visible, for example). Without making drastic changes to the design, moving them up was simply not possible.

**Comment by lxmarinkovic** [comment]
> The problem is that we just don't have enough space at the top to fit all of these options, so we moved them to the bottom.
> 
> I'm willing to entertain an accessible design that somehow exposes the language options higher up, but we'd need it to work in a responsive way all the way down to mobile. If someone wants to propose something, we can consider it, but I don't think it's worth the team spending any time on.

I genuinely believe that the lang. selector should be on top but simplified (abbreviated or just flag) version with reduced length, so it fits on the left side of Donate button. When it is about light/dark switch, I agree that it should remain on the bottom

**Comment by nzakas** [comment]
Thanks for the explanation @SaraSoueidan.

Given that, we aren’t going to move forward with making changes here.
