### ISSUE TITLE
Suggestion: Sticky navbar on the website

### ISSUE THREAD

**Issue by AakashTyagi354** [eslint/eslint.org#337]
### What problem do you want to solve?

Hey I have a suggestion for UI , Can we make navbar stick at the top so that it is always percent when ever we scroll through website.
 

### What do you think is the correct solution?

Making navbar stick at the top.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. We decide against a sticky navbar during the redesign as we don't think it's worth taking up the extra vertical space when navigating between all the top level pages isn't a common use case.
