### ISSUE TITLE
Bug: `run npm run install:playground` text appears before playground mounts on the page

### ISSUE THREAD

**Issue by shanpriyan** [eslint/eslint.org#341]
### URL(s)

https://eslint.org/play/

### What did you do?

Opened the URL https://eslint.org/play/

### What did you expect to happen?

`run npm run install:playground before running playground` should appear only in development.

### What actually happened?

`run npm run install:playground before running playground` appeared before playground mounted on the page

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

https://user-images.githubusercontent.com/42532987/189477478-9916c268-b064-454a-8a2b-8df81a85ec5b.mp4

PR which included the `run npm run install:playground before running playground` text : #307

**Comment by harish-sethuraman** [comment]
Thanks for reporting this issue. I'd like to pick this
