### ISSUE TITLE
Bug: no-shadow hoist functions section zh-cn translation incorrect

### ISSUE THREAD

**Issue by liushenf** [eslint/eslint.org#360]
### URL(s)

http://eslint.cn/docs/rules/no-shadow#hoist-functions

### What did you do?

After the first sample in "hoist: functions", the here is a sentence as below:
`虽然 if 语句中的 let b 在 function声明之前，该示例是正确的。`

But in the English version (https://eslint.org/docs/latest/rules/no-shadow#hoist-functions), the sentence is:
`Although let b in the if statement is before the function declaration in the outer scope, it is incorrect.`

### What did you expect to happen?

So, the zh-ch translation should be:
`... ，该示例是不正确的。`

### What actually happened?

The current translation is:
`... ，该示例是正确的。`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Sorry, we don’t own or maintain eslint.cn so we can’t help.
