### ISSUE TITLE
Suggestion: add proper og:images for rules 

### ISSUE THREAD

**Issue by harish-sethuraman** [eslint/eslint.org#362]
### What problem do you want to solve?

currently when a user shares eslint url through social media it shows ESLint logo as og image and that doesn't make sense. We could improve this with something better like the one github shows. I'd suggest we show the rule name, description that we have already about the rule  and if the rule is recommended or not along with some way to depict it has fix or not. That way we could convey more through the preview image.

![Screenshot 2022-10-25 at 5 55 01 PM](https://user-images.githubusercontent.com/32865581/198366957-13fa6fab-c358-43b3-9d50-3b16aa72f26e.png)

### What do you think is the correct solution?

Since the rules are static and are limited to a list we could actually write the layout for the preview image and write a node script to generate images by reading the `rules.json`. We could use `@resvg/resvg-js` to convert the layout to png. We can do this as pre commit task when there is new change in rules directory if we want to? 

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I'm in for implementing if we take this 😛 . We can further explore other areas too. I suggested rules alone because it seems to have very short and crisp descriptions which will look great on the og preview

**Comment by nzakas** [comment]
I’m all for this. I’d suggest we also look at services that can generate these images on the fly. I know there are a couple out there that allow you to pass in a background image and then text to overlay. I think that’s a better long-term solution than needing to generate and check in every image.

First step seems like to come up with a design for what these images should look like.

**Comment by harish-sethuraman** [comment]
By on the fly I assume you are talking about something like this? https://github.com/vercel/satori/
https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation 

Reason why I did not suggest generating on the fly. 
1. We might need to deploy the service separately
2. We have to maintain it despite the number of rules are kinda fixed and not very dynamic
3. Someone else can also hit the API directly to abuse the API which can be handled though

Im also up with doing this if we consider all the above points.

**Comment by kecrily** [comment]
> We have to maintain it despite the number of rules are kinda fixed and not very dynamic

Maybe we just need a template and generate the og image at build time.

> First step seems like to come up with a design for what these images should look like.

I tried to create a [draft](https://og-playground.vercel.app/?share=jVU7juNGEL1Kg06Hvf3_CGMHS9vYgJsZEywmoSRqRIMShSE10mCxoS_g1AZsX80n8BH8usmmNMIGm4h8zarX71VVtz5nq25dZ4vsft28kOH0_WO2aeszOeWbY9uS7fhYPuWnbTPUj9kPj3tCbmLDT77qWrLLq-PQTUEI61-eyKlZD1tEWv2YkZemPr3vzoCMMGI1MVidohF_qIYtWePrR2Wo1lYQwSlnXpZSUcaNJVxSZzwvpKSWCR-wcdYTYMkNv8aMCZniS8GoMtwkvgKYKxeg8EwT7qnXSgZshEbaBXtn3YM0SHe8SOvATjJFJhppKTc6wrgLsFS2TCKUotrZKDqKBLbGqSAympjxZHKKL1MRRroCEKvTZoiylBmFrKjFXOOg9WHSXozrfPYWaZidvd-U-hPatGnaFl34zjHHfhbo0P270JqvNYpRz5R0oLcwo0zJNXXYlmA3aa0oOORIwQmjxmsRWmKxgNYzwh3VQjvCPihHlZe8UB7OucU3zUIN5CVNQx6ql3hLYyjnOmxrFGoLaLRHx8DpvCcz9tRabwIO4ZJRK4QqE5uGeatNkbbTlmoON0kI1E3a8PohCjbF6CB-TO5CnhRQF9wjP_BCRhnLY9CU4EOpglGpvQujAl3wBX9pwUUjWHhb0E8fMcMyaFeMConZvcJGCAyvpFqBCthDVRh5izlQsGicL6Wg8K8F5Y7JMIPCcx-wtHjGGUS7ZowZlB7exvhSS0w4Q0FGtgJYWRieNgOESAxV1AKaCw5aH1AxgZEPaXEdpXNSxDxl4TqU0jodMEchAxbOmHjeNY6EocJqHmVbgToaymJ-PEqcXzBMWi9SfBmLgCGb-ELNtAoHe9ov1TDpmfGo9yHpn57Xh0K9l6KQt4fi_h0uu_g-4fmK3L3mggz1ecj1uSWbbj_ky65dX917-y4_9nVb931e96vqUCdKcCT6mS4yCTDtlrm6Ivmx6au27U7kuN_XK3BVz69kpCOrbfVcrYb6uX_LfMsdb_O4gUpS-3rX3Mi9snbOQyHSB0L-_fO3OepK_W0O6Q7VqhlQGPYm_b-__vj7W_Jvkn7_52tJl_f0Nj6zu6w7DE2377PF5yz-PWULx9hdtq2bp-2QLVQA63p5fMoWm6rt67us3nW_Nr-8HsI_5XCKCDyhQj_tlvU6WwzPx_rLl_8B)

![image](https://user-images.githubusercontent.com/45708948/198524940-7d3c9ac4-6229-45fa-985b-e451e884b3aa.svg)

**Comment by nzakas** [comment]
@harish-sethuraman i meant let’s find a service we can use, not one we have to maintain. That would eliminate most of the issues.

We could also use a Netlify function for this purpose.

@kecrily that looks great. 👍 

Only issue with build time generation is how long it takes. We do have a limit on Netlify jobs, so it would be helpful to get an idea about how long it would take for each build.

**Comment by harish-sethuraman** [comment]
> let’s find a service we can use

It is a very simple task, all we need is to plug a library to convert layout to png. Which takes care of most of the issues. 

> Only issue with build time generation is how long it takes. We do have a limit on Netlify jobs, so it would be helpful to get an idea about how long it would take for each build.

I tried to convert a complex svg to png with https://www.npmjs.com/package/@resvg/resvg-js and it took me 595.372ms on my device (m1 macbook pro). Or we could even convert HTML layout to svg and to png using https://github.com/vercel/satori/. HTML -> SVG conversion is still more faster using `satori` it usually takes 20 to 50 ms.

If you think it might take too much time during build. We can consider having a bot for it that updates the OG images. We could trigger the bot via some tag or command to generate new og and commit it? or periodically commit new og images?

**Comment by nzakas** [comment]
@harish-sethuraman My main goal here is to limit the complexity of generating these images. If we can offload most of the process outside of our build, that is preferable. I know it seems like a simple task, but if we are generating 300 images on every deploy, every deploy preview, for multiple translation sites, that adds up to a lot of computing that might not ever be needed. That's why I'd prefer if there was a service we could use to generate the images dynamically rather than needing to do it in bulk multiple times. (I also don't want all of those images in source control.)

If you can come up with some JS that can do the generation, we can then use a Netlify function to generate images on the fly.

**Comment by kecrily** [comment]
I plan to implement it. During evaluation, I found that satori and @vercel/og do not support netlify function. for that we need to use [its port og-edge](https://github.com/ascorbic/og-edge)
