### ISSUE TITLE
Add Mastodon link to footer

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#378]
### What problem do you want to solve?

We now have a Mastadon account! We should at it to the footer along with our other social buttons.

### What do you think is the correct solution?

Find a Mastodon image and link it to https://fosstodon.org/@eslint.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Looking for help with this one. :)

**Comment by amareshsm** [comment]
I will look into this.
