### ISSUE TITLE
Bug: Missing translation in homepage navbar for few languages

### ISSUE THREAD

**Issue by shanpriyan** [eslint/eslint.org#389]
### URL(s)

- https://hi.eslint.org/ 
![image](https://user-images.githubusercontent.com/42532987/208481164-a3043bd4-1047-4f76-9deb-cfa3e76ffb9a.png)

- https://ja.eslint.org/ 
![image](https://user-images.githubusercontent.com/42532987/208481050-d7f75712-2f69-4f0d-9f69-e61449fada3f.png)

- https://pt-br.eslint.org/ 
![image](https://user-images.githubusercontent.com/42532987/208480955-25224970-58b8-45a9-aeaa-5738943114ce.png)

### What did you do?

Visited above URLs

### What did you expect to happen?

All words in navbar should be translated according to the selected language

### What actually happened?

Few words appears in English even though the selected language is different

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kecrily** [comment]
I'm not sure if this is missing or if it's intentional; some words don't find a good translation equivalent in other languages, and that's when the original may be used directly

**Comment by amareshsm** [comment]
> I'm not sure if this is missing or if it's intentional; some words don't find a good translation equivalent in other languages, and that's when the original may be used directly

I also feel the same.

**Comment by shanpriyan** [comment]
> I'm not sure if this is missing or if it's intentional; some words don't find a good translation equivalent in other languages, and that's when the original may be used directly

if that's the case we can close this issue

**Comment by kecrily** [comment]
I checked the first PRs for these languages, and these fields were already there then, but didn't translate them, and the reviewers also didn't point them out. I think this is deliberate

---

Thank you for your meticulous discovery
