### ISSUE TITLE
Bug: Local development broken

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#397]
### URL(s)

(All)

### What did you do?

Tried writing a new blog post with a date in the future.

### What did you expect to happen?

I expected the blog post to be visible at https://localhost:2022/blog. We had this set up so that future posts would be shown locally to make it easier to debug, but then would not be shown on the live site.

I also expected the blog to update whenever I edit the Markdown file.

### What actually happened?

The blog post does not show up on the blog page, and even if I hack it so that it does show up, the blog post is not being watched for changes so I need to stop and restart the server just to see changes.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

There were a bunch of changes made to `package.json` that I believe are causing both of these issues.

For some reason, the environment variable `CONTEXT` is now being set here:

```
        "watch:eleventy": "cross-env CONTEXT=dev eleventy --serve --port=2022",
```

However, we specifically expect no `CONTEXT` to determine whether or not to [show future blog posts](https://github.com/eslint/eslint.org/blob/main/src/_11ty/collections/blogposts.js#L9).

I'm not sure why watching isn't working otherwise. It appears to work for `.js` files but it does not work for `.md` files.

**Comment by amareshsm** [comment]
https://github.com/eslint/eslint.org/blob/427e3bc27aff8e5189b240cb36187234d8281d63/package.json#L20
Renaming the `CONTEXT`  env fixes this issue.
