### ISSUE TITLE
Add Mastadon links to the team page

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#414]
### What problem do you want to solve?

Right now, the [team page](https://eslint.org/team) shows icons for both GitHub and Twitter for each user who has them specified. GitHub just recently added the ability to specify a Mastadon profile as well, so we should add that to the team page for each member who has them.

### What do you think is the correct solution?

Create a Mastadon icon, update the [GraphQL query](https://github.com/eslint/eslint.org/blob/main/tools/fetch-team-data.js) to pull it, and display the Mastadon icon with a link to each member's profile (when available).

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by kecrily** [comment]
I will do this. Also do we need to show personal website and other social media together?

**Comment by nzakas** [comment]
I think if we do personal website, github, twitter, and mastadon, that would be enough. 👍 

(Forgot about personal website but I've definitely wanted to add that for a while.)

**Comment by kecrily** [comment]
I did some research on this and neither the GitHub GraphQL API nor the REST API currently provide support for custom social media links.

```graphql
query { 
  user(login: "kecrily") {
   # ...
  }
}
```

<https://api.github.com/users/kecrily>

I've submitted a ticket for support for this, and I am waiting for a response.

**Comment by nzakas** [comment]
Thanks for the update. 👍

**Comment by kecrily** [comment]
After investigating again, I found that they had already provided this API in March, but just didn't get back to me in passing.

I will implement it as soon as possible.
