### ISSUE TITLE
Update eslint/playground README to point to this repository

### ISSUE THREAD

**Issue by not-my-profile** [eslint/eslint.org#422]
The https://github.com/eslint/playground repository has been subsumed by this repository (https://github.com/eslint/playground/issues/93) but still shows up in search results on GitHub. I think the README there should be updated to point to this repository ... because otherwise people who find the old repository will be confused where the playground source has gone.

(Opening this issue here since the other repository has been archived.)

**Comment by Rec0iL99** [comment]
@not-my-profile thanks for the issue. I don't think it's possible to update the README of a repo on GitHub once it has been archived.

> We recommend that you close all issues and pull requests, as well as update the README file and description, before you archive a repository.

> To make changes in an archived repository, you must unarchive the repository first.

[Github Docs](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival)

**Comment by nzakas** [comment]
I feel like archiving the repo is a good indication that you shouldn't be looking there for active code, and I don't want to lose the archived date, so we'll just live with it as-is. Thanks.

**Comment by not-my-profile** [comment]
Yes archiving is indeed a good indication that you shouldn't look there ... it just doesn't tell you where to look instead. I'd consider a reference to the new location to be much more important than an archived date. That date is preserved anyway in #268.
