### ISSUE TITLE
Allow the selection of "all rules" in the playground

### ISSUE THREAD

**Issue by not-my-profile** [eslint/eslint.org#423]
### What problem do you want to solve?

The [playground](https://eslint.org/play/) currently apparently only lets you select specific rules and does not provide a way to select all rules (which would be useful to find out whether or not eslint has a rule for a specific piece of code).

`eslint:all` has been implemented in https://github.com/eslint/eslint/commit/f804397f1a8d809c454d739b4adeb0a44e58600e but that option does not appear to be surfaced by the playground.

### What do you think is the correct solution?

Provide a way to select all rules in the playground.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by not-my-profile** [comment]
Actually I think it might make more sense to simply allow the provision of an arbitrary `eslintrc` configuration, like the [typescript-eslint playground](https://typescript-eslint.io/play/) supports.

**Comment by nzakas** [comment]
I'll leave this for @eslint/website-team to comment on, if anyone has any ideas.

At this point, we can't just allow any arbitrary config file to be uploaded because we are in the middle of changing the config system.

**Comment by harish-sethuraman** [comment]
There are some things to addressed here. 
- If we consider allowing the eslint:all option to select all rules, Should we include it inside the dropdown? 
If we do so we can't maintain a state where rules can be opted out if not wanted
- If we show the use all rules option outside the dropdown as a checkbox we can show intermediate state as well. But would like to know how it would look in the UI

@kecrily @amareshsm Thoughts?

**Comment by harish-sethuraman** [comment]
@eslint/website-team following up on this as it has been open for a long time?

**Comment by amareshsm** [comment]
I missed this thread. Thanks for the reminder. 

FMPOV: I am ok with giving a checkbox to enable all the rules. Clicking on  `enable all the rules` (checked) option will add all the rules, and clicking again (unchecked) will remove all the rules.

And also we can give an option to reset to defaults. By clicking on reset to defaults it will reset all the configs to the default state. 

![image](https://user-images.githubusercontent.com/30730124/230687535-463a4beb-195d-4c3d-ad72-3d76e7161bfd.png)


PS: I will pick this one if we are implementing it.

**Comment by kecrily** [comment]
I like the checkbox idea, but we should need an intermediate state to indicate that part of the rule is checked.

**Comment by amareshsm** [comment]
> @amareshsm are you picking this? we have decided to settle up with keeping the checkbox that selects all the rules and delselects all the rules when un-checked.

yes, I will send a PR. Assigning it to myself.

**Comment by shanpriyan** [comment]
Hey @amareshsm can I take up this issue if you haven't started yet

**Comment by Rec0iL99** [comment]
Since @amareshsm has not responded, @harish-sethuraman, @shanpriyan one of you could take up the task.

**Comment by amareshsm** [comment]
@Rec0iL99  thanks for the remainder. I missed this thread. I am done with the work and will raise PR soon.
