### ISSUE TITLE
Bug: ::selection background not visible

### ISSUE THREAD

**Issue by ziyunfei** [eslint/eslint.org#431]
### URL(s)

https://eslint.org/

### What did you do?

1. Enable chrome://flags/#enable-experimental-web-platform-features flag and restart Chrome.
2. Open the ESLint homepage and select some text.
 
![image](https://user-images.githubusercontent.com/1276859/233285225-67136032-a793-48d1-bc72-960794b4d04e.png)

### What did you expect to happen?

.

### What actually happened?

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

https://github.com/w3c/csswg-drafts/issues/6641

**Comment by ziyunfei** [comment]
> What feature in particular is breaking?

Global custom properties in :host will not be available on ::selection once Chrome ships this experimental feature named 'HighlightInheritance'.

https://github.com/eslint/eslint.org/blob/0ae984df29770b02c3bce3fd4d377b8c3b68da5e/src/assets/scss/foundations.scss#L1-L4

> What would be the fix?

Put all global variables into :root::selection at the same time.
```css
:root, :root::selection {
  ...
}
```
:root::selection, :root

> Why should we care about experimental features? 

Indeed, experimental features are subject to change, and Chrome may adjust this feature to ensure backward compatibility. However, this depends on whether the CSS Working Group will modify their draft specification. Currently, the website most affected by this change, GitHub, has not adjusted their code. Therefore, it may be best to wait and see how the situation develops before taking any action.

**Comment by nzakas** [comment]
Thanks for the explanation, that's very helpful. I'll leave this to @eslint/website-team to decide how to move forward.

**Comment by amareshsm** [comment]
> > What feature in particular is breaking?
> 
> Global custom properties in :host will not be available on ::selection once Chrome ships this experimental feature named 'HighlightInheritance'.
> 
> https://github.com/eslint/eslint.org/blob/0ae984df29770b02c3bce3fd4d377b8c3b68da5e/src/assets/scss/foundations.scss#L1-L4
> 
> > What would be the fix?
> 
> Put all global variables into :root::selection at the same time.
> 
> ```css
> :root, :root::selection {
>   ...
> }
> ```
> 
> > Why should we care about experimental features?
> 
> Indeed, experimental features are subject to change, and Chrome may adjust this feature to ensure backward compatibility. However, this depends on whether the CSS Working Group will modify their draft specification. Currently, the website most affected by this change, GitHub, has not adjusted their code. Therefore, it may be best to wait and see how the situation develops before taking any action.

Since it is an experimental feature it can change at any time. As @ziyunfei suggested we can wait and see.

**Comment by kecrily** [comment]
I don't think it will be released from experimental soon. Every experiment always takes a long time

**Comment by amareshsm** [comment]
Thanks for bringing this up. Closing the issue for now since the site is breaking only in experimental mode and aren't quite ready for a full Chrome release.
