### ISSUE TITLE
Bug: Duplicate problems in the playground are not removed when the code changes

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint.org#445]
### URL(s)

https://eslint.org/play/#eyJ0ZXh0IjoiZGVmaW5lKFtdLCBmdW5jdGlvbigpIHtcbiAgICBpZiAodHJ1ZSkge1xuICAgICAgdmFyIG15dmFyID0gMTA7XG4gICAgfSBlbHNlIGlmICh0cnVlKSB7XG4gICAgICB2YXIgbXl2YXIgPSAxMDtcbiAgICB9IGVsc2UgaWYgKHRydWUpIHtcbiAgICAgIHZhciBteXZhciA9IDEwO1xuICAgIH0gZWxzZSBpZiAodHJ1ZSkge1xuICAgICAgdmFyIG15dmFyID0gMTA7XG4gICAgfVxufSk7XG5cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiYmxvY2stc2NvcGVkLXZhciI6WyJlcnJvciJdfSwiZW52Ijp7ImVzMjAyMSI6dHJ1ZX19fQ==

### What did you do?

While looking into [this issue](https://github.com/eslint/eslint/issues/17244#issuecomment-1579870712) in the main repo, I opened the repro URL specified above, then I started adding empty lines at the top of the code editor in the playground.

### What did you expect to happen?

The list of problems in the lower part of the page should stay the same, except for the line numbers.

### What actually happened?

Duplicate problems are not removed when the code is changed, and you end up with the list getting longer and longer every time a new empty line is added, with new problems getting listed after the old ones.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
I can reproduce this, so marked accepted.

**Comment by fasttime** [comment]
Thanks for accepting this @mdjermanovic, I'll work on a fix.
