### ISSUE TITLE
Suggestion: Add yml configuration description in the rules explanations

### ISSUE THREAD

**Issue by clauBv23** [eslint/eslint.org#457]
### What problem do you want to solve?

I'm trying to configure my YML file by adding some new rules and it is being hard to find the proper configuration due to the config examples being only in JSON format.  

For example, in the [sort-imports rule](https://eslint.org/docs/latest/rules/sort-imports) only the JSON configuration example is provided. 

The same happens in the [Playground](https://eslint.org/play/) when only the JSON config file can be downloaded. 

### What do you think is the correct solution?

It would be really helpful to have also the YML configuration file examples and to have the ability to download it directly in the playground. 

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the feedback. We are actually going to be removing support for YAML configuration files going forward, so we're not going to be adding any new documentation or features to the playground. 

In the meantime, we have YAML examples in the [configuring rules](https://eslint.org/docs/latest/use/configure/rules#using-configuration-files) documentation.

**Comment by clauBv23** [comment]
Hi @nzakas thanks for your response. I didn't know Eslint was not going to stop supporting YAML. Is there a discussion/task or similar, whith this discontinuation information, timeline etc.?

**Comment by Rec0iL99** [comment]
> Hi @nzakas thanks for your response. I didn't know Eslint was not going to stop supporting YAML. Is there a discussion/task or similar, whith this discontinuation information, timeline etc.?

Sorry for the delay in replying. You can track the implementation here https://github.com/eslint/eslint/issues/13481.
