### ISSUE TITLE
Suggestion: (To change the twitter icon to it's new logo)

### ISSUE THREAD

**Issue by Tanujkanti4441** [eslint/eslint.org#477]
### What problem do you want to solve?

As twitter has a new brand logo now so it's better to change twitter's old icon in website.

### What do you think is the correct solution?

Replace it with the new one

![Screenshot 2023-10-12 at 17-06-29 Find and fix problems in your JavaScript code - ESLint - Pluggable JavaScript Linter](https://github.com/eslint/eslint.org/assets/86398394/6c0ead7c-ad6f-40ad-9612-075d962f4a80)

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sounds good to me! 👍 Go for it.
