### ISSUE TITLE
Suggestion: Explicit docs page for rule fixes and suggestions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint.org#479]
### What problem do you want to solve?

Right now, there's no single page that explains what rule fixes (`--fix`) are compared to rule suggestions. On https://eslint.org/docs/latest/rules:

* The 🔧 fixers notice on top links to the [`--fix` command line option](https://eslint.org/docs/latest/use/command-line-interface#--fix): which I think can be confusing for developers accustomed to rules auto-fixing in their IDE. It's not clear that these  two "fixers" are the same mechanism.
* The 💡 suggestions notice on top links to [editor suggestions](https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions) in custom rules docs: which I think is too deep for users who just want to learn about ESLint. It's not clear that the information is relevant to all rules, not just custom ones. Info in the _"write your own custom rules"_ section is a little intimidating.

### What do you think is the correct solution?

Could we add a few sentences explaining that:

* Each rule's report may optionally provide "fixes" that should be safe to run (i.e. don't cause logical changes).
    * Fixes may be applied with `--fix` and via editor extensions
* Each rule's report may optionally provide "suggestions" that may be unsafe to run (i.e. cause logical changes)
    * Suggestions may only be applied via editor extensions

I'm not sure where this info would go. https://eslint.org/docs/latest/use/core-concepts#rules links straight to the rules list in https://eslint.org/docs/latest/rules/. So under the _Core Concepts > Rules_ subheading, perhaps a subheading with a name like _Fixes and Suggestions_? Or two subheadings, _Fixes_ and _Suggestions_?

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Linked context: https://github.com/typescript-eslint/typescript-eslint/pull/7666#discussion_r1359895416. I'd like the docs in typescript-eslint.io to link to canonical/core ESLint docs. But for rule fixers and suggestions it seems like we don't have great options.

Anecdotally speaking, I've been giving a lot of conference/meetup talks recently about linting, and the slides explaining this info have been very well received. A lot of folks have expressed to me that they didn't know the differences before.

**Comment by harish-sethuraman** [comment]
Can we possibly do that in the rules listing page? Because we already have a part for explaining what the emojis are denoting? I'd like to hear more thoughts on this too

[`Rules in ESLint are grouped by type to help you understand their purpose. Each rule has emojis denoting:`](https://eslint.org/docs/latest/rules/)

**Comment by nzakas** [comment]
> I'm not sure where this info would go. https://eslint.org/docs/latest/use/core-concepts#rules links straight to the rules list in https://eslint.org/docs/latest/rules/. So under the Core Concepts > Rules subheading, perhaps a subheading with a name like Fixes and Suggestions? Or two subheadings, Fixes and Suggestions?

That seems like a good location for that info. 👍

**Comment by nzakas** [comment]
Oops, hit Return too soon. I'm not sure if we need subheadings or if adding a couple of sentences will suffice.  I'd imagine the explanations will be relatively short so subheadings may be overkill. I'd say put together a PR and we can workshop it. :)
