### ISSUE TITLE
Switch Playground to flat config

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint.org#507]
In the last TSC meeting, we agreed to switch the ESLint Playground to flat config, as soon as possible. It doesn't need to wait for the ESLint v9.0.0 final release, but it should be done before the ESLint v9.0.0 final release.

A brief overview of tasks:

* We didn't mention whether the Playground will keep using ESLint v8.56.0 or switch to v9 prerelease versions. Assuming that it will keep using v8.56.0 until the final v9.0.0, we need to pass `configType: "flat"` to the Linter constructor to make it work in flat config mode.
* ECMA Version, Source Type, and ECMA Features should map to config properties `languageOptions.ecmaVersion`, `languageOptions.sourceType`, and `languageOptions.parserOptions.ecmaFeatures` respectively. We should also add `"commonjs"` to the list of source types.
* Environments. This doesn't exist in flat config mode, so we should either drop this entirely or consider using the `globals` package in the Playground, in which case we would rename Environments to e.g., Globals, and the config file that Playground creates for download would `import` the globals package. Thoughts?
* Rules. I think this stays pretty much the same, except that Linter in flat config mode validates rule configurations so we probably don't need to use `@eslint/eslintrc` anymore.
* If possible, it would be nice to support existing links to the Playground by translating configurations to the new format so that the links can keep working as before.
* Download this config file - this would now create an `eslint.config.js` file, in the flat config format of course. Perhaps there should be an option to choose between ESM and CommonJS formats?

**Comment by snitin315** [comment]
I'll work on this.

I think we can drop support for Environments initially and replace it later with globals if it's required or requested by users.

**Comment by snitin315** [comment]
@mdjermanovic What's the equivalent API for `linter.getRules()` in the new config system?

https://github.com/eslint/eslint.org/blob/56e2580e4ea9da16ba28bb6d7a8ee169bcd3ca15/src/playground/App.js#L17

**Comment by mdjermanovic** [comment]
> @mdjermanovic What's the equivalent API for `linter.getRules()` in the new config system?
> 
> https://github.com/eslint/eslint.org/blob/56e2580e4ea9da16ba28bb6d7a8ee169bcd3ca15/src/playground/App.js#L17

There's no equivalent at the moment. We could do `new Linter({ configType: "eslintrc" }).getRules()` until we figure this out.

**Comment by snitin315** [comment]
Yeah, that's what I went ahead with. 

Should we also mention this in the migration guide for v9? I was unable to find any reference for Node.js API migration.

**Comment by mdjermanovic** [comment]
> Should we also mention this in the migration guide for v9? I was unable to find any reference for Node.js API migration.

Linter API changes are here (an example with `getRules()` is at the end):

https://eslint.org/docs/head/use/migrate-to-9.0.0#flat-linter

**Comment by snitin315** [comment]
Nice, somehow I missed it.

**Comment by nzakas** [comment]
Can someone open an issue in the eslint repo describing the use case and what's now missing?

**Comment by snitin315** [comment]
Created an issue to track - https://github.com/eslint/eslint/issues/18103

**Comment by vlakoff** [comment]
I just discovered that `/* eslint-env browser */` directive has become ineffective in the playground. Defining environments has also disappeared from the side menu.

So, for now the only solution to clear the errors is to add `/* globals document, window, setTimeout, etc. */`? Are there plans to bring back the directive?

**Comment by mdjermanovic** [comment]
> So, for now the only solution to clear the errors is to add `/* globals document, window, setTimeout, etc. */`? Are there plans to bring back the directive?

Yes, `/* globals */` is the only way to specify globals in the Playground now.

`/* eslint-env */` directives will not be supported because the new config system doesn't support specifying environments.
