### ISSUE TITLE
Bug: (camelcase misinformation)

### ISSUE THREAD

**Issue by angular-moon** [eslint/eslint.org#518]
### URL(s)

https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgY2FtZWxjYXNlOiBbXCJlcnJvclwiXSovXG5cbmNvbnN0IEZsT1dfSU5TUEVDVCA9ICdmbG93X2luc3BlY3QnO1xuXG5jb25zdCBtYXRjaEZsb3dzID0gdXNlU2VsZWN0b3IoKHN0YXRlKSA9PiBzdGF0ZVtGbE9XX0lOU1BFQ1RdKVxuXG4iLCJvcHRpb25zIjp7ImVudiI6e30sInJ1bGVzIjp7fSwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9LCJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUifX19

### What did you do?

config camelcase 

### What did you expect to happen?

don't emit error

### What actually happened?

emit error

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
This repository is about the eslint website. for issues related to eslint functionality please submit them at https://github.com/eslint/eslint

**Comment by aladdin-add** [comment]
also, please provide more info why you think it's a bug. 🙏

**Comment by aladdin-add** [comment]
also, please provide more info why you think it's a bug. :

**Comment by angular-moon** [comment]
I'm sorry I mistook l for L 😂
