### ISSUE TITLE
Bug: Ad only showing on the homepage

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#520]
### URL(s)

https://eslint.org
https://eslint.org/blog

### What did you do?

When to the homepage and then the blog page

### What did you expect to happen?

The ad shows up in the upper-right on both pages.

### What actually happened?

The ad shows up only on the homepage and is missing from all other pages (blog posts, team, etc.)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by amareshsm** [comment]
I will pick this.

**Comment by nzakas** [comment]
Thanks. Don't forget to move to "Implementing" on the Triage board. (I'll do it this time.)

**Comment by amareshsm** [comment]
Tried two approaches 
1. #525 - converted ad.html file to ad.macro.html and passed carbon ads and ethical ads data as params.
2. #524 - used Nunjucks variables to store carbon ads and ethical ads data.

Not sure which approach will be efficient. IMO 2nd approach looks good. Please share your suggestions.

**Comment by nzakas** [comment]
Thanks for digging in this. I think I found a simpler solution:
https://github.com/eslint/eslint.org/pull/527
