### ISSUE TITLE
Bug: (build:playground) linter Critical dependency

### ISSUE THREAD

**Issue by debughao** [eslint/eslint.org#521]
### URL(s)

https://eslint.org/

### What did you do?

when i npm run build:playground，webpack build WARNING：
WARNING in ./src/playground/node_modules/eslint/lib/linter/rules.js 59:32-60
Critical dependency: the request of a dependency is an expression

### What did you expect to happen?

no  Critical dependency

### What actually happened?

WARNING in ./src/playground/node_modules/eslint/lib/linter/rules.js 59:32-60
Critical dependency: the request of a dependency is an expression

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by amareshsm** [comment]
> This is just a warning and shouldn't affect your ability to work with the playground. Is there some other problem you're seeing?

+1


https://github.com/eslint/eslint/blob/c4d26fd3d1f59c1c0f2266664887ad18692039f3/lib/linter/rules.js#L49-L51

We are getting this warning since we are using the expression inside the `require` statement to load dynamically.

**Comment by amareshsm** [comment]
Since the warning isn't causing any issues, so closing this issue.
