### ISSUE TITLE
Suggestion: [playground]alert item add Disabled button. 

### ISSUE THREAD

**Issue by zhangenming** [eslint/eslint.org#548]
### What problem do you want to solve?

we can Disabled an rule quickly.

### What do you think is the correct solution?

 add Disabled button. 

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for submitting this. While I understand what you're going for, the point of filing an issue is to provide details as to what change you'd like to make and why you'd like to make it. One sentence really isn't enough for us to evaluate.

**Comment by zhangenming** [comment]
> what change you'd like to make
add a button like this
![image](https://github.com/eslint/eslint.org/assets/21235555/cce07ab9-04e7-4b0c-a838-ad9a939951bf)



> why you'd like to make it.
 can quickly remove rules that I know I don't want

**Comment by nzakas** [comment]
Seems reasonable to me, although the button should be labeled "Disable" or maybe "Ignore"?

And not sure if we should just remove it from the configuration or set to "off".

Would like some thoughts from @eslint/eslint-team

**Comment by snitin315** [comment]
I think the label should be `Disable` and we should turn it off instead of removing from the config.

**Comment by mdjermanovic** [comment]
If we'd add a "Config" button that would scroll to the rule's config, as proposed in https://github.com/eslint/eslint.org/issues/550, then we might not need this button as the user can there easily remove it or set it to `"off"`, whichever they prefer.

**Comment by harish-sethuraman** [comment]
Should we also disable the rule inline with `eslint-disable` comment or should we rather remove it from the list of selected rules?

**Comment by snitin315** [comment]
> If we'd add a "Config" button that would scroll to the rule's config, as proposed in #550, then we might not need this button as the user can there easily remove it or set it to "off", whichever they prefer.


I think it makes more sense to implement https://github.com/eslint/eslint.org/issues/550, this would solve both issues.

**Comment by nzakas** [comment]
I think a "Disable" button is a much better user experience if your goal is to disable a rule. Clicking on "config" and then needing to shift focus, then edit the config, then go back to the editor is a lot of steps.

**Comment by amareshsm** [comment]
I too feel the same disable button is better. 

> I think a "Disable" button is a much better user experience if your goal is to disable a rule. Clicking on "config" and then needing to shift focus, then edit the config, then go back to the editor is a lot of steps.

**Comment by nzakas** [comment]
I think it depends on what use case we want to focus on. If we think that people disabling a rule is the more common case, then it makes sense to have a "Disable" button. If we think that people modifying the rule's config is more common and that disabling is a less common case, then just having a "Config" button makes sense.
