### ISSUE TITLE
Suggestion: [playground] each alert item add a "config(or setting, or...)" button.

### ISSUE THREAD

**Issue by zhangenming** [eslint/eslint.org#550]
### What problem do you want to solve?

when page alert you hava some error
You have to copy the rule name and search to find it .. 

can we add a config button at each alert item right
so  when click this button
the right side will scroll to this item , so that user-friendly configuration

### What do you think is the correct solution?

Add a button

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment]
Hi @zhangenming, could you provide more context?

![Screenshot 2024-04-09 at 12 17 37 AM](https://github.com/eslint/eslint.org/assets/56463684/052fa1af-117e-40cf-b417-635e1aa0ed00)

Do you mean clicking on a button somewhere in this alert will take the user to the specific rule configuration?

**Comment by zhangenming** [comment]
yes
like right next to the "fix"button ,
then  the "rules list" will auto scroll this item

**Comment by snitin315** [comment]
We can add a `See config` button next to the `Fix` button. However, this would be unavailable for errors reported via inline-rules.

**Comment by nzakas** [comment]
Closing due to age.
