### ISSUE TITLE
Bug: Used screen width is too narrow

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint.org#580]
### URL(s)

https://eslint.org/ and others

### What did you do?

Visited the eslint.org homepage on my 1920 x 1080 laptop.

### What did you expect to happen?

It used to look like this:

![image](https://github.com/eslint/eslint.org/assets/44349756/5d21f676-b01c-4975-9888-a310ca689d2b)

### What actually happened?

Now it looks like this:

![image](https://github.com/eslint/eslint.org/assets/44349756/ecb72c02-72dc-42d9-85db-8aa1c7065f60)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I believe this was changed in https://github.com/eslint/eslint.org/pull/578

**Comment by harish-sethuraman** [comment]
will send a PR for this
