### ISSUE TITLE
Implement links for participation in the OpenJS Foundation ESP Program

### ISSUE THREAD

**Issue by joeeames** [eslint/eslint.org#594]
### What problem do you want to solve?

The new ESP program (https://openjsf.org/ecosystem-sustainability-program) allows projects to participate and gain funding for further work. This issue is to provide a discussion forum for the changes required for ESLint to participate in the program. I will make a list of recommended changes, and then once we have final approval, HeroDevs or the ESLint maintainers will produce the PR's to effect the changes.

### What do you think is the correct solution?

ESLint Site Change Recommendations

Summary

1. Add a “support” page with content as outlined below
2. Need an official “version support policy” statement
3. Add a banner to the homepage that is dismissable, with a cookie that keeps the banner dismissed on future sessions, indicating that v7 and below are out of support, and v8 will soon be out of support
4. Add a new top level nav item that points to the new version support page
5. Add a “Previous Verisions” item to the documentation version dropdown list
6. Add a link to the “Previous Versions” page on the left navigation
7. Add to the Github README file a summary of the support information

## 1. New “Support” Page

—---------------------------------------------------------- start of content 
Version Support Status

We support only the latest version of ESLint. Major versions less than 9 are no longer supported. 

Still on versions older than 9? Here are your options
Upgrade to the latest version
If possible, the best solution is to upgrade to the supported version of ESLint as this keeps you safe and gives you the best performance and features.
Purchase extended commercial support:
If you cannot migrate, but require a secure version of ESLint, you can obtain commercial security support for your applications to keep them secure.
Stay on the unsupported versions
If your application has no security requirements, then you can stay on one of the unsupported versions of ESLint, but be aware that this comes with multiple risks.
Commercial Support
The following companies offer commercial support services for jQuery.

HeroDevs offers security and compatibility support for EOL versions of ESLint through the OpenJS Ecosystem Sustainability Program and is an approved commercial support vendor. You can find out more about their Never Ending Support options here.

—---------------------------------------------------------- end of content 

## 2. Banner on Home Page
The following banner will be added to the home page with the following changes: 
![banner](https://github.com/eslint/eslint.org/assets/1072285/a1fb61fe-afc2-47bc-bd03-252b860aa609)

## 3. New Top Level Nav Item
In the screenshot shown above, a new nav item will be added named “Version Support”

## 4. Previous Versions item in version dropdown on documentation pages
This link will point at the Version Support Page
![dropdown](https://github.com/eslint/eslint.org/assets/1072285/e08ddfa9-5645-4392-adb9-da66bc221c93)

## 4. Link on documentation left nav
A link will be added to the docs left nav pointing at the Version Support page
![sidenav](https://github.com/eslint/eslint.org/assets/1072285/1af1f14f-1e48-4152-8d97-460b0f489267)

## 5. Github README changes
The following section will be added to the github README file right before “Code of Conduct”

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for putting this together. Some thoughts/questions:

1. Is the banner intended to talk about ESLint v7, which was last released in 2021? Might it be better to talk about ESLint v8 approaching EOL? How long prior to/after EOL does it make sense to show a banner? (I'm not a fan of persistent banners that people will just tune out.)
2. I feel like the banner being purple draws undue attention to the announcement, as purple is our highlight color. Maybe we could choose a subtler color from [our palette](https://github.com/eslint/eslint.org/blob/main/src/assets/scss/tokens/themes.scss)?
3. I really don't like "Version Support" in the top nav. It doesn't seem to fit well there. I wonder if maybe we can put it elsewhere? Maybe it could replace the "Development" section on the homepage hero (right side) so that "Version Support" is right under the versions? And then maybe a link in the footer?
4. I also feel like "Version Support" in the sidenav on the docs is way too high up. It seems like it should either be right above or right below "Migrate to 9.x".
5. It seems like the right place for a big purple banner would be on an EOL'ed versions docs page. So when ESLint v8.x goes EOL, I think it would make sense to ensure people are aware that they're viewing an EOL'ed version.

So, my overall feedback is I feel like the proposed treatment is a bit heavy-handed for the intended audience, which is a small subsection of our userbase. I'd like to find a treatment that is findable but also not something most people need to skip over.

Do you have some examples from other partners that we could look at to consider alternatives?

**Comment by joeeames** [comment]
just an update @nzakas, all great comments, I'm working with our designer to produce new screenshots reflecting your feedback. 

Some detailed replies

1. all good points. will adjust.
2. great idea, I'll propose more options
3. Good call. I think taking it out of the top nav is just fine. I personally try to think from the perspective of someone who is asking "is the version I'm using still supported?" and then can they find the information with a reasonable amount of effort and minimal confusion. 

In reference still to #3, I realize that I personally missed the most obvious place. 
![eslint-homepage](https://github.com/eslint/eslint.org/assets/1072285/4162cdf0-1b5c-49fb-a070-90636a733c7a)

How about adding the link there? I'll get a more reasonable modkup from our designer.
4. given the above, and how easy it will be to find from the home page, I'm good with this moving down to be above the migration link
5. totally agree.

**Comment by joeeames** [comment]
also, re: your question in #1 about the length of time, we recommend at least 6 months, and for a HUGE upgrade that can be difficult and lots of work, then 12 to 18 months.

**Comment by joeeames** [comment]
Have some alternatives for the banner color (and text) and for a link on the home page to the version support link. 

Home page link #1 
![home page link 1](https://github.com/eslint/eslint.org/assets/1072285/0ea5feb1-fcce-4365-a450-f3de3a73fda1)

option 2
![home page link 2](https://github.com/eslint/eslint.org/assets/1072285/2695c80f-322a-4d42-a6ec-e549f655d1a2)

option 3
![home page link 3](https://github.com/eslint/eslint.org/assets/1072285/c87351a7-cf4f-44a9-abc2-b2c8c7e830d6)


And here's some banner color options, with adjusted text

#1 
![banner 1](https://github.com/eslint/eslint.org/assets/1072285/4e1fe2d3-680e-4e63-ab90-7078cc2f42ac)

#2 
![banner 2](https://github.com/eslint/eslint.org/assets/1072285/5bf0cb9e-a4d1-48fe-85f4-379f37486b5d)

#3
![banner 3](https://github.com/eslint/eslint.org/assets/1072285/e8d4cf9a-384d-4a3f-9dd8-1af1383fc58c)

#4 
![banner 4](https://github.com/eslint/eslint.org/assets/1072285/9a71e8bb-53b3-49f6-b0db-266f1312200b)

#5 
![banner 5](https://github.com/eslint/eslint.org/assets/1072285/fcf78e08-9f99-444d-8d43-bce64e289b2d)

**Comment by fasttime** [comment]
The banner color in design #<span/>5 is a bit of clash IMO. The other designs look good, I think they would fit well without changes also in the dark theme.

Oh, and the light blue lines in design #<span/>1 shouldn't be there, right? It looks like an artifact of the selection tool.

![image](https://github.com/eslint/eslint.org/assets/6367844/daeffa1d-1573-429f-8f7f-be8734738562)

**Comment by joeeames** [comment]
I'll make adjustments to both issues later today

**Comment by nzakas** [comment]
@joeeames what will be the landing page for ESLint support? We can start adding links in various places.

**Comment by joeeames** [comment]
apologize for the delay. I'm running solo on all the OpenJS projects, so things are a bit behind.

I LOVE the PR. Especially the content on the support page. 

Do you still want to put up a banner about the EOL of v8? If so it seems that color #1 is the best match (that's my favorite, I'm loving grays)

For the docs pages (for example: https://deploy-preview-600--new-eslint.netlify.app/docs/latest/) still need a couple items:

1) add a link to the Version Support page on the dropdown of the versions
2) add a link to the Version Support page right above the migration guide link.

Finally  (3) we still need to put a short summary on the github README as well. I can mock that up if desired.

**Comment by amareshsm** [comment]
> apologize for the delay. I'm running solo on all the OpenJS projects, so things are a bit behind.
> 
> I LOVE the PR. Especially the content on the support page.
> 
> Do you still want to put up a banner about the EOL of v8? If so it seems that color #1 is the best match (that's my favorite, I'm loving grays)
> 
> For the docs pages (for example: https://deploy-preview-600--new-eslint.netlify.app/docs/latest/) still need a couple items:
> 
> 1. add a link to the Version Support page on the dropdown of the versions
> 2. add a link to the Version Support page right above the migration guide link.
> 
> Finally (3) we still need to put a short summary on the GitHub README as well. I can mock that up if desired.

I would like to help on completing the pending items if required.

**Comment by nzakas** [comment]
@joeeames sounds good. Do you have a specific landing page for ESLint support that we can include?

Here's what I think are the next steps:

1. Put up the v8 EOL notice on the homepage (this repo) and also in the `v8.x` branch of the `eslint/eslint` repo.
2. Add the "Version Support" link to the dropdown in the docs. That will have to be done in both `main` and in the `v8.x` branch in the `eslint/eslint` repo.
3. Add the "Version Support" link to the left nav in the docs. This must also be done in both `main` and `v8.x` in `eslint/eslint`.
4. Merge the Version Support page. We can do this as soon as we know the final landing page for HeroDevs.
5. Update the README in `eslint/eslint`. 

@amareshsm happy to have you work on this.

After all that is done, I think we should do a formal blog announcement about the partnership and formally announce v8 EOL.

**Comment by joeeames** [comment]
I'm working on the link. I'll have that today. 

it sounds like that's the only thing needed on my end, am I correct in that?

**Comment by nzakas** [comment]
Yup. Once we have that, @amareshsm can finish up the remaining tasks.

**Comment by joeeames** [comment]
sorry it took so long. our guy was out of town and then I was:

https://www.herodevs.com/support/eslint-nes?utm_source=ESLintWebsite&utm_medium=ESLintWebsite&utm_campaign=ESLintNES&utm_id=ESLintNES

**Comment by nzakas** [comment]
@joeeames no worries. I've updated the link on this PR: https://github.com/eslint/eslint.org/pull/600. Once the CI passes, I can merge it and we can move on to the other tasks.

@amareshsm can you please prioritize doing the work for this issue?

**Comment by amareshsm** [comment]
> @joeeames no worries. I've updated the link on this PR: #600. Once the CI passes, I can merge it and we can move on to the other tasks.
> 
> @amareshsm can you please prioritize doing the work for this issue?

Yes sure. 

Need help with adding  "Version Support" link to the left navigation in the docs? Any suggestions would be appreciated.

**Comment by nzakas** [comment]
@amareshsm https://www.11ty.dev/docs/plugins/navigation/#overriding-the-url

**Comment by nzakas** [comment]
I've updated our tracking issue here:
https://github.com/eslint/eslint/issues/18621

Once we get the EOL banners up, we can close this issue.

**Comment by amareshsm** [comment]
> I've updated our tracking issue here: [eslint/eslint#18621](https://github.com/eslint/eslint/issues/18621)
> 
> Once we get the EOL banners up, we can close this issue.

sure. I am working on it.

**Comment by nzakas** [comment]
Thanks @amareshsm! 🙏

**Comment by nzakas** [comment]
All right, we've got the banners on the homepage and on the v8.x docs site, so closing. Thanks @amareshsm! 

Please follow https://github.com/eslint/eslint/issues/18621 for further updates.
