### ISSUE TITLE
Bug: Alignment of search bar cancel icon on the documentation page is broken

### ISSUE THREAD

**Issue by zaryanz** [eslint/eslint.org#606]
### URL(s)

https://eslint.org/docs/latest/

### What did you do?

This bug can be reproduced by searching for something in the search bar.
Tested on Firefox 128.0.2 (64-bit), Google Chrome 126.0.6478.183 (Official Build) (arm64) - macOS Ventura 13.3.1

### What did you expect to happen?

Ideally, the cancel icon should be center aligned.

### What actually happened?

Currently, the cancel icon appears at the bottom of the search bar, which does not look right.
<img width="358" alt="Screenshot 2024-07-25 at 12 45 23 PM" src="https://github.com/user-attachments/assets/2e9259a8-3bf6-4a9e-9818-6276d2cf558d">

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by harish-sethuraman** [comment]
Can you send similar fixes as https://github.com/eslint/eslint/pull/18682/files?

**Comment by amareshsm** [comment]
@zaryanz Thanks for pointing out the issue. It has already been fixed in https://github.com/eslint/eslint.org/pull/603 but it hasn't been deployed yet.
