### ISSUE TITLE
Suggestion: Add diamond tier to GitHub Sponsors

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#632]
### What problem do you want to solve?

Add diamond tier to GitHub Sponsors

### What do you think is the correct solution?

Add diamond tier to GitHub Sponsors

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by harish-sethuraman** [comment]
I guess only TSC have this option?

**Comment by nzakas** [comment]
Yes. That's why it's assigned to me.

**Comment by nzakas** [comment]
Completed.
