### ISSUE TITLE
Suggestion: Add sponsors to READMEs on eslint.org and code-explorer

### ISSUE THREAD

**Issue by amareshsm** [eslint/eslint.org#649]
### What problem do you want to solve?

On the main [ESLint README](https://github.com/eslint/eslint/?tab=readme-ov-file#technology-sponsors), [rewrite README](https://github.com/eslint/rewrite?tab=readme-ov-file#sponsors), [markdown README](https://github.com/eslint/markdown) and [js README](https://github.com/eslint/js?tab=readme-ov-file#sponsors) repos we have sponsors listed but haven't listed in `code-explorer` and `eslint.org` repo.

### What do you think is the correct solution?

Add the sponsor's info in `code-explorer` and `eslint.org` as well. 

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

If we have intentionally chosen not to include sponsor information in `eslint.org` and `code-explorer`, please feel free to close this issue.

**Comment by nzakas** [comment]
Sounds good to me.

**Comment by amareshsm** [comment]
Completed via https://github.com/eslint/eslint.org/pull/654 https://github.com/eslint/code-explorer/pull/69
