### ISSUE TITLE
Suggestion: Include thanks.dev sponsors

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#653]
### What problem do you want to solve?

Right now, we are getting sponsorship money from thanks.dev, but we aren't displaying any of those sponsors on the website.

### What do you think is the correct solution?

Update the `fetch-sponsors.js` script to include thanks.dev sponsors.

Here's the API:
https://api.thanks.dev/v1/entity/gh/eslint/donors

For each donor, we should look at the last item in the `payments` array and, if the month is the current month, include them as a sponsor. For example, we are currently in October 2024, so only payments marked as `2024-10` should be included.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by harish-sethuraman** [comment]
Ill pick this

**Comment by nzakas** [comment]
Thanks!
