### ISSUE TITLE
Bug: Use Algolia DocSearch URL params

### ISSUE THREAD

**Issue by randombeeper** [eslint/eslint.org#659]
### URL(s)

https://eslint.org/blog/
https://eslint.org/docs/latest/

(Any URL that shows the "Powered By Algolia" logo and link.)

### What did you do?

Click the "Powered By Algolia" link under the search box

### What did you expect to happen?

It should go to: 
https://www.algolia.com/developers/?utm_source=eslint&utm_medium=referral&utm_content=powered_byutm_campaign=docsearch

### What actually happened?

It went to: 
https://www.algolia.com/developers/?utm_source=eslint&utm_medium=referral

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Hello, this is a small thing but as the owner of the DocSearch program at Algolia I'm trying to get all uses of DocSearch to be using the correct backlink to us. Adding these params will help us keep track of our customers, usage, and referral traffic. I would greatly appreciate it!

**Comment by harish-sethuraman** [comment]
@randombeeper seems like you missed a `&` after `powered_by`?? can you confirm?

**Comment by randombeeper** [comment]
@harish-sethuraman yes, I did! thanks for noticing and reacting so quickly, looks like you added it. It is appreciated.
