### ISSUE TITLE
Suggestion: Add Bluesky handles alongside Mastodon and Twitter/X

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint.org#668]
### What problem do you want to solve?

Right now, eslint.org includes Mastodon and Twitter links for blog authors and its own social media. Bluesky has become a lot more popular recently and a lot of people have moved over to it. ESLint even has its own Bluesky handle now: https://bsky.app/profile/eslint.org 🦋
 

### What do you think is the correct solution?

Anywhere that allows a Mastodon and/or Twitter/X handle, let's also add a Bluesky handle allowance.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

Split out of #664 -> #669, which has a proposed implementation.

**Comment by amareshsm** [comment]
I am 👍  for this change.

**Comment by nzakas** [comment]
Good idea. :+1:
