### ISSUE TITLE
Suggestion: support 3rd party plugins in Playground

### ISSUE THREAD

**Issue by rakleed** [eslint/eslint.org#681]
### What problem do you want to solve?

To easily create examples of reproducing the problem for third-party plugins, you have to use StackBlitz or https://github.com/ota-meshi/eslint-online-playground. In StackBlitz, you actually have to configure everything yourself, and there is no convenient error message display. As for the `@ota-meshi solution`, I don’t know how long it will support it, so I would like to see it in a tool from ESLint.

### What do you think is the correct solution?

Add the ability to install and configure third-party plugins.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
This is a lot of work and we just don't have the bandwidth to investigate, so closing.

If anyone coming across this would like to donate their time to come up with a design for this, feel free to leave a comment.
